import React, { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { AreaChart, Area, BarChart, Bar, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
import { supabase } from '../supabaseClient';

const Dashboard = () => {
  const [data, setData] = useState(null);
  const [logs, setLogs] = useState([]);
  const [allLessons, setAllLessons] = useState([]);
  const [farmers, setFarmers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showLogoutConfirm, setShowLogoutConfirm] = useState(false);
  const [activeView, setActiveView] = useState('overview'); // 'overview', 'lessons', 'farmers', 'sms', 'reports'
  
  // Lesson/Module management states
  const [showAddLesson, setShowAddLesson] = useState(false);
  const [selectedModuleForNewLesson, setSelectedModuleForNewLesson] = useState('');
  const [localModules, setLocalModules] = useState([]);
  const [newModuleName, setNewModuleName] = useState('');
  const [showAddModule, setShowAddModule] = useState(false);
  
  const [newLesson, setNewLesson] = useState({
    title: '', content: '', language: 'en', sms_text: '', target_animals: 'cow'
  });
  
  // Expanded modules in accordion
  const [expandedModules, setExpandedModules] = useState([]);
  
  const [showAddTranslation, setShowAddTranslation] = useState(false);
  const [parentLesson, setParentLesson] = useState(null);
  const [translationData, setTranslationData] = useState({
    title: '', content: '', sms_text: '', language: 'lg', theme: ''
  });
  
  const [isSaving, setIsSaving] = useState(false);
  const [smsSending, setSmsSending] = useState(false);
  const [smsResult, setSmsResult] = useState(null);
  const [smsError, setSmsError] = useState(null);

  // Advanced reports states
  const [reportsAnimalFilter, setReportsAnimalFilter] = useState('all');
  const [reportsLanguageFilter, setReportsLanguageFilter] = useState('all');

  const navigate = useNavigate();

  const fetchAllData = async () => {
    try {
      const [analyticsRes, logsRes, lessonsRes, farmersRes] = await Promise.all([
        fetch(`${import.meta.env.VITE_API_URL}/analytics/summary`),
        fetch(`${import.meta.env.VITE_API_URL}/sms/logs`),
        fetch(`${import.meta.env.VITE_API_URL}/lessons`),
        fetch(`${import.meta.env.VITE_API_URL}/farmers`)
      ]);
      
      const analyticsJson = await analyticsRes.json();
      const logsJson = await logsRes.json();
      const lessonsJson = await lessonsRes.json();
      const farmersJson = await farmersRes.json();
      
      setData(analyticsJson);
      setLogs(logsJson);
      setAllLessons(lessonsJson);
      setFarmers(farmersJson);
      
      // Extract unique modules (English themes or whichever themes exist)
      const englishLessons = lessonsJson.filter(l => l.language === 'en');
      const themes = Array.from(new Set(englishLessons.map(l => l.theme || 'General')));
      const allThemes = Array.from(new Set(lessonsJson.map(l => l.theme || 'General')));
      const mergedThemes = Array.from(new Set([...themes, ...allThemes]));
      
      setLocalModules(mergedThemes);
      
      // Expand first module by default
      if (mergedThemes.length > 0 && expandedModules.length === 0) {
        setExpandedModules([mergedThemes[0]]);
      }
    } catch (err) {
      console.error("Connection error:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAllData();
  }, []);

  // Update local modules whenever allLessons changes to capture new additions
  useEffect(() => {
    if (allLessons.length > 0) {
      const themes = Array.from(new Set(allLessons.map(l => l.theme || 'General')));
      setLocalModules(prev => {
        const merged = Array.from(new Set([...themes, ...prev]));
        return merged;
      });
    }
  }, [allLessons]);

  const getAutoGeneratedCode = (modName) => {
    if (!modName) return "LES1";
    const prefix = modName.slice(0, 3).toUpperCase().replace(/[^A-Z]/g, '') || "LES";
    const prefixLessons = allLessons.filter(l => l.code.toUpperCase().startsWith(prefix));
    const uniqueCodes = Array.from(new Set(prefixLessons.map(l => l.code)));
    return `${prefix}${uniqueCodes.length + 1}`;
  };

  const handleAddModule = () => {
    if (!newModuleName.trim()) return;
    const cleanModName = newModuleName.trim();
    if (!localModules.includes(cleanModName)) {
      setLocalModules([...localModules, cleanModName]);
      setExpandedModules([...expandedModules, cleanModName]);
    }
    setNewModuleName('');
    setShowAddModule(false);
  };

  const handleSaveLesson = async () => {
    setIsSaving(true);
    const code = getAutoGeneratedCode(selectedModuleForNewLesson);
    const payload = {
      code,
      title: newLesson.title,
      content: newLesson.content,
      language: newLesson.language,
      theme: selectedModuleForNewLesson,
      sms_text: newLesson.sms_text,
      target_animals: newLesson.target_animals || 'cow',
      checklist: ''
    };
    
    try {
      const res = await fetch(`${import.meta.env.VITE_API_URL}/lessons/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      if (res.ok) {
        setShowAddLesson(false);
        setNewLesson({
          title: '', content: '', language: 'en', sms_text: '', target_animals: 'cow'
        });
        await fetchAllData();
      } else {
        const errData = await res.json();
        alert(`Error: ${errData.detail || 'Failed to save lesson'}`);
      }
    } catch (e) {
      console.error(e);
      alert("Connection error while saving lesson");
    } finally {
      setIsSaving(false);
    }
  };

  const handleSaveTranslation = async () => {
    setIsSaving(true);
    const payload = {
      code: parentLesson.code,
      title: translationData.title,
      content: translationData.content,
      language: translationData.language,
      theme: translationData.theme || parentLesson.theme, // Translation of theme/module name!
      sms_text: translationData.sms_text,
      target_animals: parentLesson.target_animals || 'cow',
      checklist: parentLesson.checklist || ''
    };
    
    try {
      const res = await fetch(`${import.meta.env.VITE_API_URL}/lessons/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      if (res.ok) {
        setShowAddTranslation(false);
        setTranslationData({
          title: '', content: '', sms_text: '', language: 'lg', theme: ''
        });
        setParentLesson(null);
        await fetchAllData();
      } else {
        const errData = await res.json();
        alert(`Error: ${errData.detail || 'Failed to save translation'}`);
      }
    } catch (e) {
      console.error(e);
      alert("Connection error while saving translation");
    } finally {
      setIsSaving(false);
    }
  };

  const handleSendDailyFeedSMS = async () => {
    setSmsSending(true);
    setSmsResult(null);
    setSmsError(null);
    try {
      const response = await fetch(`${import.meta.env.VITE_API_URL}/sms/send-daily-feed`, {
        method: 'POST'
      });
      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.detail || "Failed to send daily feed SMS");
      }
      const data = await response.json();
      setSmsResult(data);
      
      // Proactively refresh logs
      const logsRes = await fetch(`${import.meta.env.VITE_API_URL}/sms/logs`);
      const logsJson = await logsRes.json();
      setLogs(logsJson);
    } catch (err) {
      console.error(err);
      setSmsError(err.message || "An unexpected error occurred while sending SMS.");
    } finally {
      setSmsSending(false);
    }
  };

  const getInitials = (username) => {
    if (!username) return 'FM';
    const parts = username.split(/[\s_.-]+/);
    if (parts.length >= 2) {
      return (parts[0][0] + parts[1][0]).toUpperCase();
    }
    return username.slice(0, 2).toUpperCase();
  };

  const getAvatarBg = (username) => {
    const colors = [
      'bg-emerald-100 text-emerald-800 border-emerald-200',
      'bg-indigo-100 text-indigo-800 border-indigo-200',
      'bg-rose-100 text-rose-800 border-rose-200',
      'bg-amber-100 text-amber-800 border-amber-200',
      'bg-teal-100 text-teal-800 border-teal-200',
      'bg-purple-100 text-purple-800 border-purple-200'
    ];
    if (!username) return colors[0];
    const code = username.charCodeAt(0) + (username.charCodeAt(1) || 0);
    return colors[code % colors.length];
  };

  const toggleAccordionModule = (modName) => {
    if (expandedModules.includes(modName)) {
      setExpandedModules(expandedModules.filter(m => m !== modName));
    } else {
      setExpandedModules([...expandedModules, modName]);
    }
  };

  const confirmLogout = async () => {
    await supabase.auth.signOut();
    navigate('/');
  };

  // --- CSV Exports Helpers ---
  const exportToCSV = (filename, headers, rows) => {
    const csvContent = "data:text/csv;charset=utf-8,\uFEFF" 
      + [headers.join(","), ...rows.map(r => r.map(val => `"${String(val).replace(/"/g, '""')}"`).join(","))].join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", filename);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportFarmers = () => {
    const headers = ["ID", "Username", "Email", "Phone Number", "Preferred Language", "Farmed Animals", "SMS Subscribed", "Bio"];
    const rows = farmers.map(f => [
      f.id, f.username, f.email, f.phone_number, f.preferred_language, f.farmed_animals, f.is_subscribed_to_sms ? "Yes" : "No", f.bio || ""
    ]);
    exportToCSV("care4animals_farmers_directory.csv", headers, rows);
  };

  const handleExportLessons = () => {
    const headers = ["ID", "Code", "Title", "Module/Theme", "Language", "Target Animals", "SMS Summary", "Content"];
    const rows = allLessons.map(l => [
      l.id, l.code, l.title, l.theme || "General", l.language, l.target_animals || "cow", l.sms_text || "", l.content
    ]);
    exportToCSV("care4animals_curriculum_registry.csv", headers, rows);
  };

  const handleExportSMSLogs = () => {
    const headers = ["Log ID", "Recipient Phone", "Message Body", "Status", "Provider Message ID", "Error Log", "Created At"];
    const rows = logs.map(l => [
      l.id, l.phone_number, l.message_body, l.status, l.provider_message_id || "", l.error_log || "", l.created_at
    ]);
    exportToCSV("care4animals_sms_traffic_history.csv", headers, rows);
  };

  if (loading) {
    return (
      <div className="flex h-screen items-center justify-center bg-background">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto"></div>
          <p className="mt-4 text-on-surface-variant font-medium animate-pulse">Syncing AgriAnalytics Data...</p>
        </div>
      </div>
    );
  }

  const curveData = [
    { name: 'Mon', value: 30 }, { name: 'Tue', value: 45 }, { name: 'Wed', value: 35 },
    { name: 'Thu', value: 50 }, { name: 'Fri', value: 48 }, { name: 'Sat', value: 60 },
    { name: 'Sun', value: 55 },
  ];

  // Filters logic for Reports Tab
  const filteredFarmersForReports = farmers.filter(f => {
    const animalMatch = reportsAnimalFilter === 'all' || (f.farmed_animals || '').toLowerCase().includes(reportsAnimalFilter.toLowerCase());
    const languageMatch = reportsLanguageFilter === 'all' || f.preferred_language === reportsLanguageFilter;
    return animalMatch && languageMatch;
  });

  return (
    <div className="flex min-h-screen bg-[#FDFCFB] text-on-background font-inter overflow-x-hidden">
      {/* Sidebar Navigation */}
      <aside className="fixed left-0 top-0 h-full w-[280px] bg-primary flex flex-col py-8 shadow-md z-50">
        <div className="px-6 mb-10 text-white">
          <Link to="/" className="flex items-center gap-3 mb-2 group">
            <img src="/care4animals.png" alt="Care4Animals Logo" className="w-12 h-12 object-contain bg-white rounded-xl p-0.5 shadow-lg shadow-black/20 group-hover:scale-105 transition-transform" />
            <span className="font-manrope text-xl font-bold text-on-primary tracking-tight">Care4Animals</span>
          </Link>
          <p className="text-on-primary-container text-[12px] font-semibold uppercase tracking-wider ml-1">Precision Farming</p>
          <div className="mt-4 p-3 bg-white/5 border border-white/10 rounded-2xl">
            <p className="text-on-primary-container text-[9px] font-bold uppercase tracking-wider mb-2">Supported by:</p>
            <div className="flex items-center gap-3">
              <img src="/wts_logo.png" alt="WTS" className="h-4 object-contain filter brightness-0 invert" />
              <div className="h-3 w-px bg-white/20" />
              <img src="/bugema_logo.png" alt="Bugema" className="h-6 object-contain filter brightness-0 invert" />
            </div>
          </div>
        </div>
        
        <nav className="flex-1 space-y-2 px-2">
          <SidebarItem icon="dashboard" label="Dashboard" active={activeView === 'overview'} onClick={() => setActiveView('overview')} />
          <SidebarItem icon="menu_book" label="Lessons" active={activeView === 'lessons'} onClick={() => setActiveView('lessons')} />
          <SidebarItem icon="groups" label="Farmers" active={activeView === 'farmers'} onClick={() => setActiveView('farmers')} />
          <SidebarItem icon="sms" label="SMS Traffic" active={activeView === 'sms'} onClick={() => setActiveView('sms')} />
          <SidebarItem icon="bar_chart" label="Reports" active={activeView === 'reports'} onClick={() => setActiveView('reports')} />
          
          <div className="pt-4 mt-4 border-t border-primary-container/30">
            <button 
              onClick={() => setShowLogoutConfirm(true)}
              className="w-full text-on-primary-container hover:text-red-200 hover:bg-red-900/20 rounded-lg flex items-center px-6 py-3 gap-3 transition-all duration-200 active:scale-[0.98]"
            >
              <span className="material-symbols-outlined">logout</span>
              <span className="font-semibold text-[12px]">Logout</span>
            </button>
          </div>
        </nav>

        <div className="px-6 py-4 border-t border-primary-container mt-auto">
          <button 
            onClick={() => {
              if (localModules.length > 0) {
                setSelectedModuleForNewLesson(localModules[0]);
              }
              setShowAddLesson(true);
            }}
            className="w-full bg-[#E7F3E8] text-[#2D5A27] hover:bg-[#2D5A27] hover:text-white py-2.5 rounded-lg font-semibold text-[12px] flex items-center justify-center gap-2 transition-all"
          >
            <span className="material-symbols-outlined text-[18px]">add</span>
            New Lesson
          </button>
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="ml-[280px] min-h-screen flex-1 bg-[#FDFCFB]">
        {/* Top Navigation Bar */}
        <header className="flex justify-between items-center h-16 px-8 bg-white border-b border-slate-100 sticky top-0 z-40">
          <div className="flex items-center gap-8">
            <h2 className="text-[#2D5A27] font-manrope text-[22px] font-black tracking-tight">
              {activeView === 'overview' && 'Curriculum Overview'}
              {activeView === 'lessons' && 'Curriculum Builder & Accordion'}
              {activeView === 'farmers' && 'Registered Farmers Directory'}
              {activeView === 'sms' && 'Branded SMS Broadcast & History'}
              {activeView === 'reports' && 'Advanced AgriAnalytics & Export Center'}
            </h2>
          </div>
          
          <div className="flex items-center gap-6 flex-1 justify-end">
            <div className="flex items-center gap-2 p-1 pl-3 pr-1 bg-slate-50 rounded-full border border-slate-100">
              <span className="font-bold text-[12px] text-slate-600">Admin Portal</span>
              <div className="w-8 h-8 rounded-full bg-[#2D5A27] flex items-center justify-center text-white font-bold text-xs shadow-sm">
                AD
              </div>
            </div>
          </div>
        </header>

        {/* Page Content */}
        <div className="p-8 space-y-8 max-w-7xl mx-auto">
          
          {/* VIEW: OVERVIEW */}
          {activeView === 'overview' && (
            <>
              {/* Metric Cards Row */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 animate-fadeIn">
                <MetricCard 
                  label="Total Course Content" 
                  value={allLessons.length || 0} 
                  icon="auto_stories" 
                  trend="+12%" 
                  trendText="vs last month"
                  accentColor="border-b-[#2D5A27]"
                  iconBg="bg-green-50"
                  iconColor="text-[#2D5A27]"
                />
                <MetricCard 
                  label="Active Languages" 
                  value={Array.from(new Set(allLessons.map(l => l.language))).length || 3} 
                  icon="translate" 
                  trendText="LG, EN, SW ready"
                  accentColor="border-b-amber-500"
                  iconBg="bg-amber-50"
                  iconColor="text-amber-700"
                />
                <MetricCard 
                  label="Farmers Registered" 
                  value={farmers.length || 0} 
                  icon="groups" 
                  trend="+18% opt-in rate" 
                  trendColor="text-[#2D5A27]"
                  accentColor="border-b-blue-500"
                  iconBg="bg-blue-50"
                  iconColor="text-blue-600"
                />
              </div>

              {/* Charts Section */}
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="lg:col-span-2 bg-white rounded-2xl border border-slate-100 shadow-sm p-6">
                  <div className="flex justify-between items-center mb-6">
                    <div>
                      <h4 className="text-[#1A1C1E] font-manrope text-[18px] font-black">Curriculum Engagement</h4>
                      <p className="text-slate-400 text-[13px]">Active lesson completions across all learning modules</p>
                    </div>
                  </div>
                  
                  <div className="h-[280px] w-full">
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={curveData}>
                        <defs>
                          <linearGradient id="colorPrimary" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%" stopColor="#2D5A27" stopOpacity={0.1}/>
                            <stop offset="95%" stopColor="#2D5A27" stopOpacity={0}/>
                          </linearGradient>
                        </defs>
                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f3f4" />
                        <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#8e9390', fontSize: 11}} />
                        <YAxis axisLine={false} tickLine={false} tick={{fill: '#8e9390', fontSize: 11}} />
                        <Tooltip contentStyle={{borderRadius: '12px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'}} />
                        <Area type="monotone" dataKey="value" stroke="#2D5A27" strokeWidth={3} fillOpacity={1} fill="url(#colorPrimary)" />
                      </AreaChart>
                    </ResponsiveContainer>
                  </div>
                </div>

                {/* Language Distribution Card */}
                <div className="bg-white rounded-2xl border border-slate-100 shadow-sm flex flex-col p-6">
                  <h4 className="text-[#1A1C1E] font-manrope text-[18px] font-black mb-1">Language Distribution</h4>
                  <p className="text-slate-400 text-[13px] mb-6">Content availability by language code</p>
                  
                  <div className="flex-1 flex flex-col justify-center space-y-6">
                    <ProgressBar label="Luganda (LG)" count={`${allLessons.filter(l => l.language === 'lg').length} Lessons`} percentage={Math.round((allLessons.filter(l => l.language === 'lg').length / (allLessons.length || 1)) * 100) || 0} color="bg-[#2D5A27]" />
                    <ProgressBar label="English (EN)" count={`${allLessons.filter(l => l.language === 'en').length} Lessons`} percentage={Math.round((allLessons.filter(l => l.language === 'en').length / (allLessons.length || 1)) * 100) || 0} color="bg-amber-500" />
                    <ProgressBar label="Swahili (SW)" count={`${allLessons.filter(l => l.language === 'sw').length} Lessons`} percentage={Math.round((allLessons.filter(l => l.language === 'sw').length / (allLessons.length || 1)) * 100) || 0} color="bg-blue-500" />
                  </div>
                </div>
              </div>
            </>
          )}

          {/* VIEW: LESSONS WORKSPACE (Accordion Like Farmer Dashboard) */}
          {activeView === 'lessons' && (
            <div className="space-y-6 animate-fadeIn">
              
              {/* Header with actions */}
              <div className="bg-white border border-slate-100 rounded-3xl p-6 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <div>
                  <h3 className="font-manrope text-lg font-black text-slate-800">Curriculum & Modules Builder</h3>
                  <p className="text-slate-400 text-xs">Manage modules, auto-generate codes, and attach translations.</p>
                </div>
                <div className="flex items-center gap-3">
                  <button 
                    onClick={() => setShowAddModule(true)}
                    className="py-2.5 px-4 bg-[#E7F3E8] text-[#2D5A27] rounded-xl text-xs font-bold hover:bg-[#2D5A27] hover:text-white transition-all flex items-center gap-2"
                  >
                    <span className="material-symbols-outlined text-[16px]">folder_open</span>
                    Create New Module
                  </button>
                </div>
              </div>

              {/* Inline module creator */}
              {showAddModule && (
                <div className="p-6 bg-slate-50 border border-slate-200 rounded-3xl flex flex-col sm:flex-row items-end gap-4 max-w-xl animate-fadeIn">
                  <div className="flex-1 space-y-1">
                    <label className="text-[10px] font-black uppercase text-slate-400">New Module/Theme Name</label>
                    <input 
                      type="text" 
                      placeholder="e.g. Vaccination Schedules" 
                      className="w-full px-4 py-2.5 bg-white border border-slate-200 rounded-xl text-xs outline-none focus:ring-1 focus:ring-[#2D5A27]"
                      value={newModuleName}
                      onChange={e => setNewModuleName(e.target.value)}
                    />
                  </div>
                  <div className="flex gap-2">
                    <button 
                      onClick={() => setShowAddModule(false)}
                      className="py-2.5 px-4 bg-white text-slate-600 border border-slate-200 rounded-xl text-xs font-bold hover:bg-slate-100"
                    >
                      Cancel
                    </button>
                    <button 
                      onClick={handleAddModule}
                      className="py-2.5 px-4 bg-[#2D5A27] text-white rounded-xl text-xs font-bold hover:opacity-90 shadow-md shadow-[#2D5A27]/20"
                    >
                      Create Module
                    </button>
                  </div>
                </div>
              )}

              {/* Accordion Module List */}
              <div className="space-y-4">
                {localModules.length === 0 ? (
                  <div className="py-16 text-center border-2 border-dashed border-slate-100 rounded-3xl">
                    <span className="material-symbols-outlined text-[48px] text-slate-300 mb-4 animate-bounce">auto_stories</span>
                    <p className="text-slate-400 font-bold text-sm">No modules registered yet.</p>
                  </div>
                ) : (
                  localModules.map((modName, mIdx) => {
                    const isOpen = expandedModules.includes(modName);
                    
                    // Filter lessons belonging to this module
                    const moduleLessons = allLessons.filter(l => (l.theme || 'General') === modName);
                    // Extract unique lesson codes
                    const uniqueCodes = Array.from(new Set(moduleLessons.map(l => l.code)));
                    const totalLessonsCount = uniqueCodes.length;

                    return (
                      <div key={mIdx} className="bg-white rounded-[24px] border border-slate-100 overflow-hidden shadow-sm">
                        {/* Module Accordion Header */}
                        <div 
                          className="w-full flex flex-col sm:flex-row items-start sm:items-center justify-between p-5 lg:p-6 text-left hover:bg-slate-50/50 transition-all gap-4"
                        >
                          <div className="flex items-center gap-4 cursor-pointer flex-1" onClick={() => toggleAccordionModule(modName)}>
                            <div className={`w-12 h-12 rounded-2xl flex items-center justify-center ${isOpen ? 'bg-[#2D5A27] text-white' : 'bg-[#E7F3E8] text-[#2D5A27]'}`}>
                              <span className="material-symbols-outlined text-[24px]">
                                {isOpen ? 'folder_open' : 'folder'}
                              </span>
                            </div>
                            <div>
                              <h4 className="font-manrope text-base font-black text-slate-800">{modName}</h4>
                              <p className="text-slate-400 text-xs font-semibold">
                                {totalLessonsCount} unique lesson{totalLessonsCount !== 1 ? 's' : ''} in module
                              </p>
                            </div>
                          </div>
                          
                          <div className="flex items-center gap-3 w-full sm:w-auto justify-end">
                            <button
                              onClick={() => {
                                setSelectedModuleForNewLesson(modName);
                                setShowAddLesson(true);
                              }}
                              className="py-1.5 px-3 bg-[#2D5A27] text-white text-[11px] font-bold rounded-xl flex items-center gap-1 hover:opacity-90 shadow-md shadow-[#2D5A27]/10"
                            >
                              <span className="material-symbols-outlined text-[14px]">add</span>
                              Add Lesson
                            </button>
                            <button
                              onClick={() => toggleAccordionModule(modName)}
                              className="p-2 border border-slate-100 hover:bg-slate-50 rounded-full text-slate-400 transition-transform duration-200"
                              style={{ transform: isOpen ? 'rotate(180deg)' : 'rotate(0deg)' }}
                            >
                              <span className="material-symbols-outlined text-[20px]">keyboard_arrow_down</span>
                            </button>
                          </div>
                        </div>

                        {/* Accordion Lessons Grid */}
                        {isOpen && (
                          <div className="border-t border-slate-50 bg-slate-50/30 p-6 space-y-6">
                            {uniqueCodes.length === 0 ? (
                              <div className="py-12 text-center border-2 border-dashed border-slate-200/50 rounded-2xl">
                                <span className="material-symbols-outlined text-[40px] text-slate-300 mb-2">library_books</span>
                                <p className="text-slate-400 text-xs font-bold">No lessons added to this module yet.</p>
                                <button 
                                  onClick={() => {
                                    setSelectedModuleForNewLesson(modName);
                                    setShowAddLesson(true);
                                  }}
                                  className="mt-2 text-xs font-black text-[#2D5A27] underline"
                                >
                                  Write the first lesson
                                </button>
                              </div>
                            ) : (
                              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                {uniqueCodes.map((code) => {
                                  // Locate primary version (preferably en)
                                  const primaryLesson = moduleLessons.find(l => l.code === code && l.language === 'en')
                                    || moduleLessons.find(l => l.code === code);
                                  
                                  const translations = moduleLessons.filter(l => l.code === code && l.id !== primaryLesson.id);

                                  return (
                                    <div key={code} className="bg-white border border-slate-100 hover:border-[#2D5A27]/20 rounded-2xl p-5 flex flex-col gap-4 shadow-sm transition-all group">
                                      <div className="flex items-start justify-between gap-4">
                                        <div className="space-y-1">
                                          <div className="flex items-center gap-2">
                                            <span className="bg-[#2D5A27] text-white px-2 py-0.5 rounded text-[10px] font-black uppercase tracking-wider">
                                              {primaryLesson.code}
                                            </span>
                                            <span className={`px-2 py-0.5 rounded text-[10px] font-black uppercase tracking-wider ${
                                              primaryLesson.language === 'en' ? 'bg-amber-100 text-amber-800' :
                                              primaryLesson.language === 'lg' ? 'bg-purple-100 text-purple-800' : 'bg-blue-100 text-blue-800'
                                            }`}>
                                              {primaryLesson.language === 'en' ? 'English (EN)' : primaryLesson.language === 'lg' ? 'Luganda (LG)' : 'Swahili (SW)'}
                                            </span>
                                          </div>
                                          <h5 className="font-manrope text-sm font-black text-slate-800">{primaryLesson.title}</h5>
                                        </div>

                                        <button
                                          onClick={() => {
                                            setParentLesson(primaryLesson);
                                            setTranslationData({
                                              title: '', content: '', sms_text: '', language: 'lg', theme: primaryLesson.theme || ''
                                            });
                                            setShowAddTranslation(true);
                                          }}
                                          className="py-1 px-2.5 bg-[#E7F3E8] hover:bg-[#2D5A27] text-[#2D5A27] hover:text-white rounded-lg text-[10px] font-bold transition-colors flex items-center gap-1 shrink-0"
                                        >
                                          <span className="material-symbols-outlined text-[12px]">translate</span>
                                          Add Translation
                                        </button>
                                      </div>

                                      <div className="text-xs text-slate-500 leading-relaxed max-h-24 overflow-y-auto bg-slate-50 p-3 rounded-xl border border-slate-100">
                                        {primaryLesson.content}
                                      </div>

                                      {primaryLesson.sms_text && (
                                        <div className="p-3 bg-orange-50/60 border border-orange-100 rounded-xl flex items-start gap-2.5 text-xs text-orange-800">
                                          <span className="material-symbols-outlined text-[16px] text-orange-600 shrink-0 mt-0.5">sms</span>
                                          <div>
                                            <strong className="block font-black uppercase text-[8px] tracking-wider text-orange-700">SMS Broadcast Content</strong>
                                            {primaryLesson.sms_text}
                                          </div>
                                        </div>
                                      )}

                                      {/* Available Translations Display */}
                                      <div className="flex flex-wrap items-center gap-2 pt-3 border-t border-slate-100">
                                        <span className="text-[9px] font-bold text-slate-400 uppercase tracking-wider">Translations:</span>
                                        {translations.length === 0 ? (
                                          <span className="text-[10px] text-slate-400 italic font-medium">None yet</span>
                                        ) : (
                                          translations.map((tr) => (
                                            <div key={tr.id} className="inline-flex flex-col gap-0.5 bg-green-50 border border-green-200/50 p-2.5 rounded-lg w-full text-xs text-slate-700 animate-fadeIn mt-1.5">
                                              <div className="flex items-center justify-between font-bold text-[#2D5A27]">
                                                <span>{tr.language === 'lg' ? 'Luganda (LG)' : 'Swahili (SW)'}</span>
                                                <span className="text-[9px] uppercase bg-[#E7F3E8] px-1.5 py-0.2 rounded font-black">
                                                  Theme: {tr.theme}
                                                </span>
                                              </div>
                                              <div className="font-semibold text-slate-800 mt-1">{tr.title}</div>
                                              <div className="text-slate-500 mt-0.5 italic text-[11px] leading-relaxed">"{tr.content}"</div>
                                              {tr.sms_text && <div className="text-orange-700 text-[10px] mt-1 font-semibold flex gap-1 items-center">
                                                <span className="material-symbols-outlined text-[12px]">sms</span>
                                                <span>SMS: {tr.sms_text}</span>
                                              </div>}
                                            </div>
                                          ))
                                        )}
                                      </div>
                                    </div>
                                  );
                                })}
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    );
                  })
                )}
              </div>
            </div>
          )}

          {/* VIEW: REGISTERED FARMERS */}
          {activeView === 'farmers' && (
            <div className="bg-white border border-slate-100 rounded-3xl p-6 shadow-sm space-y-6 animate-fadeIn">
              <div>
                <h3 className="font-manrope text-base font-black text-slate-800">Registered Farmers Directory</h3>
                <p className="text-slate-400 text-xs">Directory of active farmers on the agricultural portal</p>
              </div>

              {farmers.length === 0 ? (
                <div className="py-16 text-center border border-dashed border-slate-100 rounded-2xl">
                  <span className="material-symbols-outlined text-[48px] text-slate-300 mb-4 animate-bounce">groups</span>
                  <p className="text-slate-400 font-bold">No registered farmers found inside the local DB.</p>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {farmers.map((farmer) => {
                    const initials = getInitials(farmer.username);
                    const avatarBg = getAvatarBg(farmer.username);
                    return (
                      <div key={farmer.id} className="bg-slate-50/50 border border-slate-100 rounded-2xl p-5 flex flex-col gap-4 hover:shadow-md transition-shadow">
                        <div className="flex items-center gap-4">
                          {farmer.profile_picture_url ? (
                            <img 
                              src={farmer.profile_picture_url} 
                              alt={farmer.username} 
                              className="w-14 h-14 rounded-full object-cover border-2 border-[#E7F3E8] shadow-sm shrink-0"
                            />
                          ) : (
                            <div className={`w-14 h-14 rounded-full border flex items-center justify-center font-black text-sm shrink-0 shadow-sm ${avatarBg}`}>
                              {initials}
                            </div>
                          )}
                          <div className="space-y-0.5">
                            <h4 className="font-manrope font-black text-slate-800 text-sm tracking-tight">{farmer.username}</h4>
                            <span className="inline-block bg-slate-100 text-slate-500 font-bold px-2 py-0.5 rounded text-[8px] uppercase">
                              Preferred: {farmer.preferred_language === 'lg' ? 'Luganda' : farmer.preferred_language === 'sw' ? 'Swahili' : 'English'}
                            </span>
                          </div>
                        </div>

                        <div className="space-y-2 text-xs">
                          <div className="flex items-center gap-2 text-slate-600">
                            <span className="material-symbols-outlined text-[16px] text-slate-400">call</span>
                            <span>{farmer.phone_number}</span>
                          </div>
                          <div className="flex items-center gap-2 text-slate-600">
                            <span className="material-symbols-outlined text-[16px] text-slate-400">mail</span>
                            <span className="truncate">{farmer.email}</span>
                          </div>
                          
                          {/* SMS OPT IN STATS */}
                          <div className="pt-2 border-t border-slate-100 flex items-center justify-between">
                            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">SMS Lesson Delivery</span>
                            <span className={`px-2 py-1 rounded-full text-[9px] font-bold ${
                              farmer.is_subscribed_to_sms 
                                ? 'bg-green-50 text-[#2D5A27] border border-green-200' 
                                : 'bg-slate-100 text-slate-500'
                            }`}>
                              {farmer.is_subscribed_to_sms ? '✔ Active Opt-In' : '❌ Subscribed (Portal)'}
                            </span>
                          </div>
                        </div>

                        {farmer.bio && (
                          <div className="bg-white p-3 rounded-xl border border-slate-100 text-[11px] text-slate-400 leading-normal italic">
                            "{farmer.bio}"
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}

          {/* VIEW: SMS TRAFFIC */}
          {activeView === 'sms' && (
            <div className="space-y-6 animate-fadeIn">
              
              {/* Premium SMS Broadcast Console Card */}
              <div className="bg-white rounded-3xl border border-slate-100 shadow-sm p-6 border-l-[8px] border-orange-500 flex flex-col gap-6">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
                  <div className="flex items-start gap-4">
                    <div className="p-3 bg-orange-50 text-orange-600 rounded-xl">
                      <span className="material-symbols-outlined text-[28px] animate-pulse">cell_tower</span>
                    </div>
                    <div>
                      <h4 className="text-[#1A1C1E] font-manrope text-[18px] font-black flex items-center gap-2">
                        Branded SMS Broadcast Console
                      </h4>
                      <p className="text-slate-400 text-[13px] mt-0.5">
                        Broadcast next sequence module lesson as a branded SMS directly to opted-in farmers.
                      </p>
                    </div>
                  </div>

                  <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-4 shrink-0">
                    <div className="bg-orange-50/70 border border-orange-100 rounded-xl p-3 max-w-[280px]">
                      <p className="text-[10px] text-orange-700 font-bold leading-relaxed">
                        📢 <strong>Subscription Check:</strong> Branded SMS lessons will automatically dispatch ONLY to active subscribers who explicitly opted in.
                      </p>
                    </div>

                    <button
                      id="send-sms-button"
                      onClick={handleSendDailyFeedSMS}
                      disabled={smsSending}
                      className={`py-3.5 px-6 rounded-xl font-bold text-[12px] uppercase tracking-wider text-white shadow-md transition-all flex items-center justify-center gap-2 shrink-0 ${
                        smsSending
                          ? 'bg-orange-300 cursor-not-allowed'
                          : 'bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-600 hover:to-amber-600 hover:scale-[1.02] active:scale-[0.98]'
                      }`}
                    >
                      {smsSending ? (
                        <>
                          <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                          Broadcasting Lessons...
                        </>
                      ) : (
                        <>
                          <span className="material-symbols-outlined text-[16px]">send</span>
                          Broadcast SMS Lessons
                        </>
                      )}
                    </button>
                  </div>
                </div>

                {/* SMS Broadcast Results */}
                {smsResult && (
                  <div className="bg-green-50 border border-green-200 rounded-xl p-4 flex flex-col gap-3 animate-fadeIn">
                    <p className="text-sm text-green-800 font-bold flex items-center gap-2">
                      <span className="material-symbols-outlined text-[18px] text-green-600">check_circle</span>
                      {smsResult.message}
                    </p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
                      {smsResult.results?.map((res, idx) => (
                        <div key={idx} className="text-xs text-green-700 bg-white/60 p-3 rounded-lg border border-green-100/50 flex flex-col gap-0.5 animate-fadeIn">
                          <span className="font-bold">Farmer: {res.farmer}</span>
                          <span>Phone: {res.phone}</span>
                          <span className="flex items-center gap-1 font-semibold">
                            Status: <strong className="uppercase">{res.status}</strong>
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {smsError && (
                  <div className="bg-red-50 border border-red-200 rounded-xl p-4 flex items-start gap-3 text-sm text-red-800 font-medium animate-fadeIn">
                    <span className="material-symbols-outlined text-red-600 shrink-0">error</span>
                    <div>
                      <p className="font-bold">Failed to broadcast</p>
                      <p className="text-xs text-red-600 mt-0.5">{smsError}</p>
                    </div>
                  </div>
                )}
              </div>

              {/* SMS Traffic Table */}
              <div className="bg-white rounded-3xl border border-slate-100 shadow-sm overflow-hidden">
                <div className="p-6 border-b border-slate-50 flex justify-between items-center">
                  <h4 className="text-slate-800 font-manrope text-base font-black">Live Outbound SMS Traffic History</h4>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse">
                    <thead className="bg-slate-50">
                      <tr>
                        <th className="px-6 py-4 font-bold text-[10px] text-slate-400 uppercase tracking-wider">Farmer</th>
                        <th className="px-6 py-4 font-bold text-[10px] text-slate-400 uppercase tracking-wider">Message Content</th>
                        <th className="px-6 py-4 font-bold text-[10px] text-slate-400 uppercase tracking-wider">Status</th>
                        <th className="px-6 py-4 font-bold text-[10px] text-slate-400 uppercase tracking-wider">Dispatched</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {logs.length === 0 ? (
                        <tr>
                          <td colSpan={4} className="px-6 py-12 text-center text-slate-400 font-bold text-xs italic">
                            No SMS broadcasts logged in history.
                          </td>
                        </tr>
                      ) : (
                        logs.map((log) => (
                          <tr key={log.id} className="hover:bg-slate-50/50 transition-colors group">
                            <td className="px-6 py-4">
                              <div className="font-bold text-slate-700 text-xs">{log.phone_number}</div>
                              <div className="text-[10px] text-slate-400">UID: {log.user_id}</div>
                            </td>
                            <td className="px-6 py-4 text-xs text-slate-500 max-w-sm truncate">{log.message_body}</td>
                            <td className="px-6 py-4">
                              <span className={`px-2.5 py-0.5 rounded-full text-[9px] font-bold uppercase ${
                                log.status === 'success' ? 'bg-green-50 text-[#2D5A27] border border-green-200' : 'bg-red-50 text-red-700 border border-red-200'
                              }`}>
                                {log.status}
                              </span>
                            </td>
                            <td className="px-6 py-4 text-xs text-slate-400">
                              {new Date(log.created_at).toLocaleString([], { dateStyle: 'short', timeStyle: 'short' })}
                            </td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          )}

          {/* VIEW: REPORTS / ADVANCED AGRIANALYTICS */}
          {activeView === 'reports' && (
            <div className="space-y-6 animate-fadeIn">
              
              {/* Top Filters & Export Panel Card */}
              <div className="bg-white border border-slate-100 rounded-3xl p-6 shadow-sm flex flex-col xl:flex-row items-stretch xl:items-center justify-between gap-6">
                <div className="flex flex-col md:flex-row items-start md:items-center gap-4">
                  <div className="space-y-1">
                    <label className="text-[9px] font-black uppercase text-slate-400 block">Filter by Animal</label>
                    <select 
                      value={reportsAnimalFilter}
                      onChange={e => setReportsAnimalFilter(e.target.value)}
                      className="px-3 py-2 bg-slate-50 border border-slate-100 rounded-xl text-xs font-semibold text-slate-700 outline-none focus:ring-1 focus:ring-[#2D5A27]"
                    >
                      <option value="all">All Animals</option>
                      <option value="cow">Cows</option>
                      <option value="goat">Goats</option>
                      <option value="chicken">Poultry</option>
                      <option value="pig">Pigs</option>
                      <option value="dog">Dogs</option>
                    </select>
                  </div>

                  <div className="space-y-1">
                    <label className="text-[9px] font-black uppercase text-slate-400 block">Filter by Language</label>
                    <select 
                      value={reportsLanguageFilter}
                      onChange={e => setReportsLanguageFilter(e.target.value)}
                      className="px-3 py-2 bg-slate-50 border border-slate-100 rounded-xl text-xs font-semibold text-slate-700 outline-none focus:ring-1 focus:ring-[#2D5A27]"
                    >
                      <option value="all">All Languages</option>
                      <option value="en">English</option>
                      <option value="lg">Luganda</option>
                      <option value="sw">Swahili</option>
                    </select>
                  </div>

                  {/* Filter reset button */}
                  {(reportsAnimalFilter !== 'all' || reportsLanguageFilter !== 'all') && (
                    <button 
                      onClick={() => { setReportsAnimalFilter('all'); setReportsLanguageFilter('all'); }}
                      className="mt-4 md:mt-0 py-1.5 px-3 bg-red-50 text-red-600 rounded-lg text-xs font-bold hover:bg-red-100 transition-colors"
                    >
                      Reset Filters
                    </button>
                  )}
                </div>

                {/* Clickable Export Buttons */}
                <div className="flex flex-wrap items-center gap-3">
                  <button 
                    onClick={handleExportFarmers}
                    className="py-2.5 px-4 bg-white border border-slate-200 text-slate-600 hover:border-[#2D5A27] hover:text-[#2D5A27] rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 shadow-sm active:scale-95"
                  >
                    <span className="material-symbols-outlined text-[16px]">download</span>
                    Export Farmers Directory
                  </button>
                  <button 
                    onClick={handleExportLessons}
                    className="py-2.5 px-4 bg-white border border-slate-200 text-slate-600 hover:border-[#2D5A27] hover:text-[#2D5A27] rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 shadow-sm active:scale-95"
                  >
                    <span className="material-symbols-outlined text-[16px]">download</span>
                    Export Lessons Registry
                  </button>
                  <button 
                    onClick={handleExportSMSLogs}
                    className="py-2.5 px-4 bg-white border border-slate-200 text-slate-600 hover:border-[#2D5A27] hover:text-[#2D5A27] rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 shadow-sm active:scale-95"
                  >
                    <span className="material-symbols-outlined text-[16px]">download</span>
                    Export SMS Log History
                  </button>
                </div>
              </div>

              {/* Reports Dashboard KPI Grid */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                
                {/* SMS Subscription Demographics */}
                <div className="bg-white border border-slate-100 rounded-3xl p-6 flex flex-col items-center text-center gap-4 shadow-sm">
                  <h4 className="font-manrope text-xs font-black uppercase tracking-wider text-slate-400">Filtered SMS Opt-In Rate</h4>
                  
                  <div className="relative w-32 h-32 flex items-center justify-center">
                    <svg className="w-full h-full transform -rotate-90" viewBox="0 0 36 36">
                      <path
                        className="text-slate-100"
                        strokeWidth="3.5"
                        stroke="currentColor"
                        fill="transparent"
                        d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                      />
                      <path
                        className="text-[#2D5A27]"
                        strokeDasharray={`${Math.round((filteredFarmersForReports.filter(f => f.is_subscribed_to_sms).length / (filteredFarmersForReports.length || 1)) * 100)}, 100`}
                        strokeWidth="3.5"
                        strokeLinecap="round"
                        stroke="currentColor"
                        fill="transparent"
                        d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                      />
                    </svg>
                    <div className="absolute text-center">
                      <span className="block font-manrope text-2xl font-black text-slate-800">
                        {Math.round((filteredFarmersForReports.filter(f => f.is_subscribed_to_sms).length / (filteredFarmersForReports.length || 1)) * 100) || 0}%
                      </span>
                      <span className="text-[9px] font-bold text-slate-400 uppercase">Opt-In Share</span>
                    </div>
                  </div>

                  <p className="text-slate-400 text-xs max-w-[200px] leading-normal mt-2">
                    Of {filteredFarmersForReports.length} filtered farmers, {filteredFarmersForReports.filter(f => f.is_subscribed_to_sms).length} actively receive SMS lessons.
                  </p>
                </div>

                {/* Livestock Filtered Demographics */}
                <div className="bg-white border border-slate-100 rounded-3xl p-6 flex flex-col justify-between shadow-sm">
                  <div>
                    <h4 className="font-manrope text-xs font-black uppercase tracking-wider text-slate-400 mb-4">Livestock Distributions (Filtered)</h4>
                    <div className="space-y-4">
                      <ProgressBar label="Cows / Dairy" count={`${filteredFarmersForReports.filter(f => (f.farmed_animals || '').toLowerCase().includes('cow')).length} Farmers`} percentage={Math.round((filteredFarmersForReports.filter(f => (f.farmed_animals || '').toLowerCase().includes('cow')).length / (filteredFarmersForReports.length || 1)) * 100)} color="bg-[#2D5A27]" />
                      <ProgressBar label="Goats / Caprine" count={`${filteredFarmersForReports.filter(f => (f.farmed_animals || '').toLowerCase().includes('goat')).length} Farmers`} percentage={Math.round((filteredFarmersForReports.filter(f => (f.farmed_animals || '').toLowerCase().includes('goat')).length / (filteredFarmersForReports.length || 1)) * 100)} color="bg-amber-500" />
                      <ProgressBar label="Poultry / Chickens" count={`${filteredFarmersForReports.filter(f => (f.farmed_animals || '').toLowerCase().includes('chicken')).length} Farmers`} percentage={Math.round((filteredFarmersForReports.filter(f => (f.farmed_animals || '').toLowerCase().includes('chicken')).length / (filteredFarmersForReports.length || 1)) * 100)} color="bg-blue-500" />
                    </div>
                  </div>
                </div>

                {/* Live System Diagnostics */}
                <div className="bg-white border border-slate-100 rounded-3xl p-6 flex flex-col justify-between shadow-sm">
                  <div className="space-y-4">
                    <h4 className="font-manrope text-xs font-black uppercase tracking-wider text-slate-400">AgriPortal System Health</h4>
                    
                    <div className="flex items-center justify-between p-3.5 bg-slate-50 border border-slate-100 rounded-2xl">
                      <div className="flex items-center gap-2">
                        <span className="relative flex h-2 w-2">
                          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                          <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                        </span>
                        <span className="text-xs font-bold text-slate-700">API Connection</span>
                      </div>
                      <span className="text-[10px] font-black uppercase text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded">Operational</span>
                    </div>

                    <div className="flex items-center justify-between p-3.5 bg-slate-50 border border-slate-100 rounded-2xl">
                      <div className="flex items-center gap-2">
                        <span className="relative flex h-2 w-2">
                          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-orange-400 opacity-75"></span>
                          <span className="relative inline-flex rounded-full h-2 w-2 bg-orange-500"></span>
                        </span>
                        <span className="text-xs font-bold text-slate-700">SMS Gateway API</span>
                      </div>
                      <span className="text-[10px] font-black uppercase text-orange-600 bg-orange-50 px-2 py-0.5 rounded">Textbee Ready</span>
                    </div>

                    <div className="flex items-center justify-between p-3.5 bg-slate-50 border border-slate-100 rounded-2xl">
                      <div className="flex items-center gap-2">
                        <span className="relative flex h-2 w-2">
                          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
                          <span className="relative inline-flex rounded-full h-2 w-2 bg-blue-500"></span>
                        </span>
                        <span className="text-xs font-bold text-slate-700">Content Cache</span>
                      </div>
                      <span className="text-[10px] font-black uppercase text-blue-600 bg-blue-50 px-2 py-0.5 rounded">Warm Pool</span>
                    </div>
                  </div>
                </div>

              </div>

              {/* Advanced Demographic List */}
              <div className="bg-white border border-slate-100 rounded-3xl p-6 shadow-sm overflow-hidden">
                <div className="pb-4 border-b border-slate-50 mb-4 flex justify-between items-center">
                  <h4 className="font-manrope text-base font-black text-slate-800">
                    Filtered Farmer Registry Details ({filteredFarmersForReports.length} matches)
                  </h4>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse">
                    <thead className="bg-slate-50">
                      <tr>
                        <th className="px-6 py-4 font-bold text-[10px] text-slate-400 uppercase tracking-wider">Farmer</th>
                        <th className="px-6 py-4 font-bold text-[10px] text-slate-400 uppercase tracking-wider">Farmed Animals</th>
                        <th className="px-6 py-4 font-bold text-[10px] text-slate-400 uppercase tracking-wider">Preferred Language</th>
                        <th className="px-6 py-4 font-bold text-[10px] text-slate-400 uppercase tracking-wider">Subscribed to SMS</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {filteredFarmersForReports.length === 0 ? (
                        <tr>
                          <td colSpan={4} className="px-6 py-12 text-center text-slate-400 font-bold text-xs italic">
                            No farmers match the current filter selection.
                          </td>
                        </tr>
                      ) : (
                        filteredFarmersForReports.map((f) => (
                          <tr key={f.id} className="hover:bg-slate-50/50 transition-colors">
                            <td className="px-6 py-4">
                              <div className="font-bold text-slate-700 text-xs">{f.username}</div>
                              <div className="text-[10px] text-slate-400">{f.email}</div>
                            </td>
                            <td className="px-6 py-4">
                              <div className="flex flex-wrap gap-1.5">
                                {f.farmed_animals ? f.farmed_animals.split(',').map((ani, aIdx) => (
                                  <span key={aIdx} className="bg-slate-100 text-slate-600 px-2 py-0.5 rounded text-[8px] font-bold uppercase shrink-0">
                                    {ani.trim()}
                                  </span>
                                )) : (
                                  <span className="text-slate-400 text-[10px] italic">Not Specified</span>
                                )}
                              </div>
                            </td>
                            <td className="px-6 py-4 text-xs font-semibold text-slate-600 uppercase">
                              {f.preferred_language || 'en'}
                            </td>
                            <td className="px-6 py-4">
                              <span className={`inline-flex items-center gap-1 text-[9px] font-bold ${
                                f.is_subscribed_to_sms ? 'text-[#2D5A27]' : 'text-slate-400'
                              }`}>
                                <span className="material-symbols-outlined text-[12px]">
                                  {f.is_subscribed_to_sms ? 'check_circle' : 'cancel'}
                                </span>
                                {f.is_subscribed_to_sms ? 'Opted-In' : 'Portal Only'}
                              </span>
                            </td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          )}

        </div>
      </main>

      {/* Logout Confirmation Modal */}
      {showLogoutConfirm && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div 
            className="absolute inset-0 bg-black/40 backdrop-blur-sm transition-opacity" 
            onClick={() => setShowLogoutConfirm(false)}
          />
          <div className="relative bg-white rounded-[32px] shadow-2xl border border-slate-100 p-8 max-w-sm w-full animate-in zoom-in-95 duration-200">
            <div className="text-center">
              <div className="w-16 h-16 bg-red-50 text-red-600 rounded-full flex items-center justify-center mx-auto mb-6 border border-red-100">
                <span className="material-symbols-outlined text-[32px]">logout</span>
              </div>
              <h3 className="text-slate-800 font-manrope text-xl font-black mb-2">Sign Out?</h3>
              <p className="text-slate-400 text-[13px] mb-8 leading-relaxed">
                Are you sure you want to end your session? You will need to login again to access the dashboard.
              </p>
              
              <div className="grid grid-cols-2 gap-4">
                <button 
                  onClick={() => setShowLogoutConfirm(false)}
                  className="py-3.5 px-4 bg-slate-50 border border-slate-200 hover:bg-slate-100 text-slate-600 rounded-2xl font-bold text-xs transition-colors"
                >
                  Stay Logged In
                </button>
                <button 
                  onClick={confirmLogout}
                  className="py-3.5 px-4 bg-red-600 hover:bg-red-700 text-white rounded-2xl font-bold text-xs transition-all shadow-lg shadow-red-200"
                >
                  Logout
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Add Lesson Modal */}
      {showAddLesson && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 overflow-y-auto">
          <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={() => setShowAddLesson(false)} />
          <div className="relative bg-white rounded-[32px] shadow-2xl border border-slate-100 p-8 max-w-lg w-full my-8">
            <h3 className="text-slate-800 font-manrope text-xl font-black mb-6">Create New Lesson</h3>
            
            <div className="space-y-4">
              <div className="space-y-1">
                <label className="text-[10px] font-black uppercase text-slate-400">Target Module</label>
                <select 
                  className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl outline-none focus:ring-1 focus:ring-[#2D5A27] text-xs font-semibold text-slate-700"
                  value={selectedModuleForNewLesson}
                  onChange={e => setSelectedModuleForNewLesson(e.target.value)}
                >
                  {localModules.map((m, idx) => (
                    <option key={idx} value={m}>{m}</option>
                  ))}
                </select>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-slate-400">Auto-Generated Code</label>
                  <input 
                    type="text" 
                    readOnly
                    className="w-full px-4 py-3 bg-slate-100 border border-slate-100 rounded-xl text-xs font-bold text-slate-500 outline-none"
                    value={getAutoGeneratedCode(selectedModuleForNewLesson)}
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-slate-400">Language</label>
                  <select 
                    className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl outline-none focus:ring-1 focus:ring-[#2D5A27] text-xs font-semibold text-slate-700"
                    value={newLesson.language}
                    onChange={e => setNewLesson({...newLesson, language: e.target.value})}
                  >
                    <option value="en">English (EN)</option>
                    <option value="lg">Luganda (LG)</option>
                    <option value="sw">Swahili (SW)</option>
                  </select>
                </div>
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-black uppercase text-slate-400">Lesson Title</label>
                <input 
                  type="text" 
                  placeholder="Lesson Title"
                  className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl text-xs outline-none focus:ring-1 focus:ring-[#2D5A27]"
                  value={newLesson.title}
                  onChange={e => setNewLesson({...newLesson, title: e.target.value})}
                />
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-black uppercase text-slate-400">Lesson Content</label>
                <textarea 
                  rows={4}
                  placeholder="Type the full body of the lesson..."
                  className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl text-xs outline-none focus:ring-1 focus:ring-[#2D5A27] resize-none"
                  value={newLesson.content}
                  onChange={e => setNewLesson({...newLesson, content: e.target.value})}
                />
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-black uppercase text-slate-400">SMS Outbound Text</label>
                <input 
                  type="text" 
                  placeholder="Brief summary text for offline SMS subscribers..."
                  className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl text-xs outline-none focus:ring-1 focus:ring-[#2D5A27]"
                  value={newLesson.sms_text}
                  onChange={e => setNewLesson({...newLesson, sms_text: e.target.value})}
                />
              </div>
            </div>

            <div className="flex gap-4 mt-8">
              <button 
                onClick={() => setShowAddLesson(false)}
                className="flex-1 py-3 bg-slate-50 border border-slate-200 hover:bg-slate-100 text-slate-600 rounded-2xl font-bold text-xs"
              >
                Cancel
              </button>
              <button 
                disabled={isSaving}
                onClick={handleSaveLesson}
                className="flex-1 py-3 bg-[#2D5A27] text-white rounded-2xl font-bold text-xs shadow-lg shadow-[#2D5A27]/20 active:scale-95 disabled:opacity-50"
              >
                {isSaving ? 'Saving...' : 'Save Lesson'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Add Translation Modal */}
      {showAddTranslation && parentLesson && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 overflow-y-auto">
          <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={() => setShowAddTranslation(false)} />
          <div className="relative bg-white rounded-[32px] shadow-2xl border border-slate-100 p-8 max-w-lg w-full my-8">
            <h3 className="text-slate-800 font-manrope text-xl font-black mb-1">Add Translation</h3>
            <p className="text-slate-400 text-xs mb-6">Create a translated version for course item <strong>{parentLesson.code}</strong></p>
            
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-slate-400">Lesson Code (Read Only)</label>
                  <input 
                    type="text" 
                    readOnly 
                    className="w-full px-4 py-3 bg-slate-100 border border-slate-100 rounded-xl text-xs font-bold text-slate-500"
                    value={parentLesson.code}
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-slate-400">Target Translation Language</label>
                  <select 
                    className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl outline-none focus:ring-1 focus:ring-[#2D5A27] text-xs font-semibold text-slate-700"
                    value={translationData.language}
                    onChange={e => setTranslationData({...translationData, language: e.target.value})}
                  >
                    <option value="lg">Luganda (LG)</option>
                    <option value="sw">Swahili (SW)</option>
                  </select>
                </div>
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-black uppercase text-slate-400">Base Title (EN Reference)</label>
                <div className="p-3 bg-slate-50 border border-slate-100 rounded-xl text-xs text-slate-500 font-medium">
                  {parentLesson.title}
                </div>
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-black uppercase text-slate-400">Module/Theme in this Language</label>
                <input 
                  type="text" 
                  placeholder="e.g. Okuzaala Enkoko (or prefilled)"
                  className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl text-xs outline-none focus:ring-1 focus:ring-[#2D5A27]"
                  value={translationData.theme}
                  onChange={e => setTranslationData({...translationData, theme: e.target.value})}
                />
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-black uppercase text-slate-400">Translated Lesson Title</label>
                <input 
                  type="text" 
                  placeholder="Translated Title"
                  className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl text-xs outline-none focus:ring-1 focus:ring-[#2D5A27]"
                  value={translationData.title}
                  onChange={e => setTranslationData({...translationData, title: e.target.value})}
                />
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-black uppercase text-slate-400">Translated Lesson Content</label>
                <textarea 
                  rows={4}
                  placeholder="Type the full body of the lesson translation..."
                  className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl text-xs outline-none focus:ring-1 focus:ring-[#2D5A27] resize-none"
                  value={translationData.content}
                  onChange={e => setTranslationData({...translationData, content: e.target.value})}
                />
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-black uppercase text-slate-400">Translated SMS Text</label>
                <input 
                  type="text" 
                  placeholder="Brief summary text in this language for offline SMS subscribers..."
                  className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl text-xs outline-none focus:ring-1 focus:ring-[#2D5A27]"
                  value={translationData.sms_text}
                  onChange={e => setTranslationData({...translationData, sms_text: e.target.value})}
                />
              </div>
            </div>

            <div className="flex gap-4 mt-8">
              <button 
                onClick={() => setShowAddTranslation(false)}
                className="flex-1 py-3 bg-slate-50 border border-slate-200 hover:bg-slate-100 text-slate-600 rounded-2xl font-bold text-xs"
              >
                Cancel
              </button>
              <button 
                disabled={isSaving}
                onClick={handleSaveTranslation}
                className="flex-1 py-3 bg-[#2D5A27] text-white rounded-2xl font-bold text-xs shadow-lg shadow-[#2D5A27]/20 active:scale-95 disabled:opacity-50"
              >
                {isSaving ? 'Saving...' : 'Save Translation'}
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

// Helper Components
const SidebarItem = ({ icon, label, active = false, onClick }) => (
  <a 
    onClick={(e) => { e.preventDefault(); onClick && onClick(); }}
    className={`${
      active ? 'bg-tertiary-container text-on-tertiary-container' : 'text-on-primary-container hover:text-on-primary hover:bg-primary-container'
    } rounded-lg mx-2 flex items-center px-4 py-3 gap-3 transition-all duration-200 active:scale-[0.98] cursor-pointer`} 
    href="#"
  >
    <span className="material-symbols-outlined">{icon}</span>
    <span className="font-semibold text-[12px]">{label}</span>
  </a>
);

const MetricCard = ({ label, value, icon, trend, trendText, trendColor = "text-green-600", accentColor, iconBg, iconColor }) => (
  <div className={`bg-surface-container-lowest p-6 rounded-xl shadow-sm border border-outline-variant border-b-4 ${accentColor} flex flex-col justify-between hover:shadow-md transition-shadow cursor-default`}>
    <div className="flex justify-between items-start">
      <div>
        <p className="text-on-surface-variant font-semibold text-[12px] uppercase tracking-wider">{label}</p>
        <h3 className="text-primary font-manrope text-[32px] font-bold mt-1">{value}</h3>
      </div>
      <div className={`p-2 ${iconBg} ${iconColor} rounded-lg`}>
        <span className="material-symbols-outlined">{icon}</span>
      </div>
    </div>
    <div className="mt-4 flex items-center gap-2">
      {trend && <span className={`${trendColor} font-semibold text-[12px]`}>{trend}</span>}
      <span className="text-on-surface-variant text-[12px]">{trendText}</span>
    </div>
  </div>
);

const ProgressBar = ({ label, count, percentage, color }) => (
  <div className="space-y-2">
    <div className="flex justify-between text-[12px] font-semibold">
      <span className="text-on-surface">{label}</span>
      <span className="text-primary">{count}</span>
    </div>
    <div className="h-4 bg-surface-container rounded-full overflow-hidden">
      <div 
        className={`h-full ${color} rounded-full transition-all duration-1000`} 
        style={{ width: `${percentage}%` }} 
      />
    </div>
  </div>
);

export default Dashboard;